services:
  taskflow-db:
    image: postgres:18
    container_name: taskflow-db
    restart: always
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
      POSTGRES_DB: taskflow
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql # <-- importante para Postgres 18+
    networks:
      - taskflow-network

  taskflow-api:
    build:
      context: .
      dockerfile: Dockerfile
      network: host # eliminar si no lo necesitas; no es común en compose
    container_name: taskflow-api
    restart: always
    depends_on:
      - taskflow-db
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - taskflow-network

volumes:
  postgres_data:

networks:
  taskflow-network:
    driver: bridge
